#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get dist-upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes
apt-get autoremove -y

echo "Rebooting in 20 sec"
sleep 20
reboot
